// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMnQAa49zjHG6l15LJLPclqYu0a1cYa0',
    appId: '1:377738380705:web:875bf5bd545aa43d64b7e0',
    messagingSenderId: '377738380705',
    projectId: 'bankapp-86993',
    authDomain: 'bankapp-86993.firebaseapp.com',
    storageBucket: 'bankapp-86993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYNdeWd0mAOQowrZ68soRZddQ4TqVZDcE',
    appId: '1:377738380705:android:46a6c20c8cb959bc64b7e0',
    messagingSenderId: '377738380705',
    projectId: 'bankapp-86993',
    storageBucket: 'bankapp-86993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXR3Imo2f80K94ESKNvsPbi7N-ffweVGQ',
    appId: '1:377738380705:ios:f017eb506ea1822664b7e0',
    messagingSenderId: '377738380705',
    projectId: 'bankapp-86993',
    storageBucket: 'bankapp-86993.appspot.com',
    iosBundleId: 'com.example.ai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXR3Imo2f80K94ESKNvsPbi7N-ffweVGQ',
    appId: '1:377738380705:ios:564ccccb43496f8a64b7e0',
    messagingSenderId: '377738380705',
    projectId: 'bankapp-86993',
    storageBucket: 'bankapp-86993.appspot.com',
    iosBundleId: 'com.example.ai.RunnerTests',
  );
}
